[workspace]

members = [
    "guessing_game",
    "hello_cargo",
    "variables",
    "functions",
    "branches",
    "rectangles",
    "restaurant",
    "generics",
    "traits",
    "minigrep",
    "closures",
    "smart_pointes",
    "limit_tracker",
    "concurrency"
]
